// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "FactoryCisum",
    defaultLocalization: "en",
    platforms: [
        .macOS(.v14),
        .iOS(.v17),
    ],
    products: [
        .library(
            name: "FactoryCisum",
            targets: ["FactoryCisum"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/CofficLab/LumiKernel.git", from: "1.0.0"),
        .package(name: "KitUIComponents", path: "../CisumUIComponents"),
        .package(url: "https://github.com/CofficLab/LumiProviders.git", from: "1.1.0"),
        .package(url: "https://github.com/CofficLab/LumiThemePack.git", from: "1.0.4"),
        .package(url: "https://github.com/CofficLab/LumiUI", from: "1.7.0"),
        .package(path: "../KitEventObservation"),
        .package(name: "KitMagic", path: "../MagicKit"),
        .package(path: "../ProviderPlugin"),
        .package(path: "../ProviderPluginManaging"),
        .package(name: "ProviderCloud", path: "../ProviderCloud"),
        .package(name: "ProviderControlView", path: "../ProviderControlView"),
        .package(name: "ProviderDevice", path: "../ProviderDevice"),
        .package(name: "ProviderAppState", path: "../ProviderAppState"),
        .package(name: "ProviderRootView", path: "../ProviderRootView"),
        .package(name: "ProviderScene", path: "../ProviderScene"),
        .package(name: "ProviderSettings", path: "../ProviderSettings"),
        // MARK: - Plugin Dependencies (直接由 Factory 装配)
        .package(name: "PluginAudio", path: "../PluginAudio"),
        .package(name: "PluginAudioCopy", path: "../PluginAudioCopy"),
        .package(name: "PluginAudioDBData", path: "../PluginAudioDBData"),
        .package(name: "PluginAudioDBView", path: "../PluginAudioDBView"),
        .package(name: "PluginAudioDemo", path: "../PluginAudioDemo"),
        .package(name: "PluginAudioDownload", path: "../PluginAudioDownload"),
        .package(name: "PluginAudioLike", path: "../PluginAudioLike"),
        .package(name: "PluginAudioPlayMode", path: "../PluginAudioPlayMode"),
        .package(name: "PluginAudioProgress", path: "../PluginAudioProgress"),
        .package(name: "PluginAudioScene", path: "../PluginAudioScene"),
        .package(name: "PluginAudioSettings", path: "../PluginAudioSettings"),
        .package(name: "PluginAudioWidgetControl", path: "../PluginAudioWidgetControl"),
        .package(name: "PluginBook", path: "../PluginBook"),
        .package(name: "PluginBookControlButtons", path: "../PluginBookControlButtons"),
        .package(name: "PluginBookDBView", path: "../PluginBookDBView"),
        .package(name: "PluginBookDBData", path: "../PluginBookDBData"),
        .package(name: "PluginBookLike", path: "../PluginBookLike"),
        .package(name: "PluginBookPlayMode", path: "../PluginBookPlayMode"),
        .package(name: "PluginBookProgress", path: "../PluginBookProgress"),
        .package(name: "PluginBookScene", path: "../PluginBookScene"),
        .package(name: "PluginBookSettings", path: "../PluginBookSettings"),
        .package(name: "PluginAudioControlButtons", path: "../PluginAudioControlButtons"),
        .package(name: "PluginFileLog", path: "../PluginFileLog"),
        .package(name: "PluginLikeButton", path: "../PluginLikeButton"),
        .package(name: "PluginOpenButton", path: "../PluginOpenButton"),
        .package(name: "PluginToast", path: "../PluginToast"),
        .package(name: "PluginPlayBack", path: "../PluginPlayBack"),
        .package(name: "PluginPlaybackHero", path: "../PluginPlaybackHero"),
        .package(name: "PluginPluginManager", path: "../PluginPluginManager"),
        .package(name: "PluginPlaybackProgress", path: "../PluginPlaybackProgress"),
        .package(name: "PluginReset", path: "../PluginReset"),
        .package(name: "PluginScene", path: "../PluginScene"),
        .package(name: "PluginSettingGeneral", path: "../PluginSettingGeneral"),
        .package(name: "PluginSettingsButton", path: "../PluginSettingsButton"),
        .package(name: "PluginStorage", path: "../PluginStorage"),
        .package(name: "PluginStore", path: "../PluginStore"),
        .package(name: "PluginWelcome", path: "../PluginWelcome"),
        .package(name: "ProviderContentView", path: "../ProviderContentView"),
        .package(name: "ProviderDocsView", path: "../ProviderDocsView"),
        .package(name: "ProviderToolbar", path: "../ProviderToolbar"),
        .package(name: "ProviderToast", path: "../ProviderToast"),
    ],
    targets: [
        .target(
            name: "FactoryCisum",
            dependencies: [
                .product(name: "KernelCore", package: "LumiKernel"),
                .product(name: "CisumUIComponents", package: "KitUIComponents"),
                .product(name: "ProviderTheme", package: "LumiProviders"),
                .product(name: "LumiThemePack", package: "LumiThemePack"),
                .product(name: "LumiUI", package: "LumiUI"),
                .product(name: "KitEventObservation", package: "KitEventObservation"),
                .product(name: "MagicKit", package: "KitMagic"),
                .product(name: "ProviderPlugin", package: "ProviderPlugin"),
                .product(name: "ProviderPluginManaging", package: "ProviderPluginManaging"),
                .product(name: "ProviderCloud", package: "ProviderCloud"),
                .product(name: "ProviderContentView", package: "ProviderContentView"),
                .product(name: "ProviderControlView", package: "ProviderControlView"),
                .product(name: "ProviderDevice", package: "ProviderDevice"),
                .product(name: "ProviderDocsView", package: "ProviderDocsView"),
                .product(name: "ProviderAppState", package: "ProviderAppState"),
                .product(name: "ProviderRootView", package: "ProviderRootView"),
                .product(name: "ProviderScene", package: "ProviderScene"),
                .product(name: "ProviderSettings", package: "ProviderSettings"),
                .product(name: "ProviderToolbar", package: "ProviderToolbar"),
                .product(name: "ProviderToast", package: "ProviderToast"),
                .product(name: "PluginAudio", package: "PluginAudio"),
                .product(name: "PluginAudioCopy", package: "PluginAudioCopy"),
                .product(name: "PluginAudioDBData", package: "PluginAudioDBData"),
                .product(name: "PluginAudioDBView", package: "PluginAudioDBView"),
                .product(name: "PluginAudioDemo", package: "PluginAudioDemo"),
                .product(name: "PluginAudioDownload", package: "PluginAudioDownload"),
                .product(name: "PluginAudioLike", package: "PluginAudioLike"),
                .product(name: "PluginAudioPlayMode", package: "PluginAudioPlayMode"),
                .product(name: "PluginAudioProgress", package: "PluginAudioProgress"),
                .product(name: "PluginAudioScene", package: "PluginAudioScene"),
                .product(name: "PluginAudioSettings", package: "PluginAudioSettings"),
                .product(name: "PluginAudioWidgetControl", package: "PluginAudioWidgetControl"),
                .product(name: "PluginBook", package: "PluginBook"),
                .product(name: "PluginBookControlButtons", package: "PluginBookControlButtons"),
                .product(name: "PluginBookDBView", package: "PluginBookDBView"),
                .product(name: "PluginBookDBData", package: "PluginBookDBData"),
                .product(name: "PluginBookLike", package: "PluginBookLike"),
                .product(name: "PluginBookPlayMode", package: "PluginBookPlayMode"),
                .product(name: "PluginBookProgress", package: "PluginBookProgress"),
                .product(name: "PluginBookScene", package: "PluginBookScene"),
                .product(name: "PluginBookSettings", package: "PluginBookSettings"),
                .product(name: "PluginAudioControlButtons", package: "PluginAudioControlButtons"),
                .product(name: "PluginFileLog", package: "PluginFileLog"),
                .product(name: "PluginLikeButton", package: "PluginLikeButton"),
                .product(name: "PluginOpenButton", package: "PluginOpenButton"),
                .product(name: "PluginToast", package: "PluginToast"),
                .product(name: "PluginPlayBack", package: "PluginPlayBack"),
                .product(name: "PluginPlaybackHero", package: "PluginPlaybackHero"),
                .product(name: "PluginPluginManager", package: "PluginPluginManager"),
                .product(name: "PluginPlaybackProgress", package: "PluginPlaybackProgress"),
                .product(name: "PluginReset", package: "PluginReset"),
                .product(name: "PluginScene", package: "PluginScene"),
                .product(name: "PluginSettingGeneral", package: "PluginSettingGeneral"),
                .product(name: "PluginSettingsButton", package: "PluginSettingsButton"),
                .product(name: "PluginStorage", package: "PluginStorage"),
                .product(name: "PluginStore", package: "PluginStore"),
                .product(name: "PluginWelcome", package: "PluginWelcome"),
            ],
            path: ".",
            exclude: [
                "README.md",
                "Tests",
            ],
            sources: ["Sources/FactoryCisum"],
            resources: [
                .process("Resources"),
            ]
        ),
        .testTarget(
            name: "FactoryCisumTests",
            dependencies: [
                "FactoryCisum",
                .product(name: "KernelCore", package: "LumiKernel"),
                .product(name: "ProviderTheme", package: "LumiProviders"),
                .product(name: "LumiThemePack", package: "LumiThemePack"),
                .product(name: "ProviderPlugin", package: "ProviderPlugin"),
                .product(name: "ProviderRootView", package: "ProviderRootView"),
                .product(name: "ProviderControlView", package: "ProviderControlView"),
                .product(name: "ProviderContentView", package: "ProviderContentView"),
            ],
            path: "Tests"
        ),
    ],
    swiftLanguageModes: [.v5]
)
